"""initial schema

Revision ID: dc19887db70e
Revises: 
Create Date: 2026-05-15 22:08:30.149213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc19887db70e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('experience_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('experience_description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone_primary', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone_secondary', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('weekdays_hours', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('saturday_hours', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sunday_hours', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('whatsapp_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_success_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_counter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('counter_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_counter_type_prefix', 'sequence_counter', ['counter_type', 'prefix'], unique=True)
    op.create_index(op.f('ix_sequence_counter_counter_type'), 'sequence_counter', ['counter_type'], unique=False)
    op.create_table('services_and_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'STAFF', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('clinic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('clinic_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_section_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_section_id'], ['hero_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_availability',
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_patients_per_slot', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doctor_availability', 'doctor_availability', ['doctor_id', 'day_of_week', 'is_available'], unique=False)
    op.create_index('idx_doctor_day', 'doctor_availability', ['doctor_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_doctor_availability_doctor_id'), 'doctor_availability', ['doctor_id'], unique=False)
    op.create_table('doctor_availability_exception',
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Enum('UNAVAILABLE', 'CUSTOM_HOURS', 'HOLIDAY', name='exceptiontype'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'exception_date', name='uq_doctor_exception_date')
    )
    op.create_index('idx_doctor_exception_date', 'doctor_availability_exception', ['doctor_id', 'exception_date'], unique=False)
    op.create_index(op.f('ix_doctor_availability_exception_doctor_id'), 'doctor_availability_exception', ['doctor_id'], unique=False)
    op.create_table('doctor_case_field_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'field_name', name='uq_doctor_field')
    )
    op.create_index(op.f('ix_doctor_case_field_preference_doctor_id'), 'doctor_case_field_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_case_field_preference_field_name'), 'doctor_case_field_preference', ['field_name'], unique=False)
    op.create_table('doctor_followup_field_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'field_name', name='uq_doctor_followup_field')
    )
    op.create_index(op.f('ix_doctor_followup_field_preference_doctor_id'), 'doctor_followup_field_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_followup_field_preference_field_name'), 'doctor_followup_field_preference', ['field_name'], unique=False)
    op.create_table('enum_types',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enum_type_active', 'enum_types', ['is_active'], unique=False)
    op.create_index('idx_enum_type_key', 'enum_types', ['key'], unique=True)
    op.create_table('finance_cash_book',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_cash_book_doctor_id'), 'finance_cash_book', ['doctor_id'], unique=False)
    op.create_table('medicine',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('potency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('potency_scale', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_created_by_doctor_id'), 'medicine', ['created_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_medicine_name'), 'medicine', ['name'], unique=False)
    op.create_table('patient',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cnic', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone_secondary', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('residential_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('referred_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('medical_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drug_allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_medications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic')
    )
    op.create_index(op.f('ix_patient_doctor_id'), 'patient', ['doctor_id'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_doctor_id', sa.Integer(), nullable=False),
    sa.Column('qualification_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_doctor_id'], ['about_doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('services_section_id', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['services_section_id'], ['services_and_treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialization_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_doctor_id'], ['about_doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stories_section_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stories_section_id'], ['patient_success_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consultation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_datetime', 'appointment', ['appointment_date', 'appointment_time'], unique=False)
    op.create_index('idx_doctor_appointments', 'appointment', ['doctor_id', 'appointment_date', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_table('doctor_medicine_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_medicine_preference_doctor_id'), 'doctor_medicine_preference', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_medicine_preference_medicine_id'), 'doctor_medicine_preference', ['medicine_id'], unique=False)
    op.create_table('enum_options',
    sa.Column('enum_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enum_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enum_type_id'], ['enum_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enum_option_active', 'enum_options', ['is_active'], unique=False)
    op.create_index('idx_enum_option_sort', 'enum_options', ['enum_type_id', 'sort_order'], unique=False)
    op.create_index('idx_enum_option_type_id', 'enum_options', ['enum_type_id'], unique=False)
    op.create_index('idx_enum_option_type_value', 'enum_options', ['enum_type', 'value'], unique=False)
    op.create_index(op.f('ix_enum_options_enum_type_id'), 'enum_options', ['enum_type_id'], unique=False)
    op.create_table('finance_cash_book_custom_field',
    sa.Column('field_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cash_book_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_book_id'], ['finance_cash_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_book_id', 'field_key', name='uq_cash_book_custom_field_key')
    )
    op.create_index('idx_cash_book_custom_field_display_order', 'finance_cash_book_custom_field', ['cash_book_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_finance_cash_book_custom_field_cash_book_id'), 'finance_cash_book_custom_field', ['cash_book_id'], unique=False)
    op.create_table('finance_transaction',
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('cash_book_id', sa.Uuid(), nullable=False),
    sa.Column('nature_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_book_id'], ['finance_cash_book.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_category_code', 'finance_transaction', ['category_code'], unique=False)
    op.create_index('idx_transaction_date', 'finance_transaction', ['cash_book_id', 'transaction_date'], unique=False)
    op.create_index('idx_transaction_deleted', 'finance_transaction', ['is_deleted'], unique=False)
    op.create_index('idx_transaction_nature_code', 'finance_transaction', ['nature_code'], unique=False)
    op.create_index(op.f('ix_finance_transaction_cash_book_id'), 'finance_transaction', ['cash_book_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_doctor_id'), 'finance_transaction', ['doctor_id'], unique=False)
    op.create_table('doctor_enum_preferences',
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('enum_option_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enum_option_id'], ['enum_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doctor_enum_pref_doctor', 'doctor_enum_preferences', ['doctor_id'], unique=False)
    op.create_index('idx_doctor_enum_pref_doctor_option', 'doctor_enum_preferences', ['doctor_id', 'enum_option_id'], unique=True)
    op.create_index('idx_doctor_enum_pref_option', 'doctor_enum_preferences', ['enum_option_id'], unique=False)
    op.create_index(op.f('ix_doctor_enum_preferences_doctor_id'), 'doctor_enum_preferences', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_enum_preferences_enum_option_id'), 'doctor_enum_preferences', ['enum_option_id'], unique=False)
    op.create_table('finance_transaction_custom_field_value',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['finance_cash_book_custom_field.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'field_id', name='uq_transaction_custom_field_value')
    )
    op.create_index(op.f('ix_finance_transaction_custom_field_value_field_id'), 'finance_transaction_custom_field_value', ['field_id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_custom_field_value_transaction_id'), 'finance_transaction_custom_field_value', ['transaction_id'], unique=False)
    op.create_table('patient_case',
    sa.Column('chief_complaint_patient', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('chief_complaint_duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('physicals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('noted_complaint_doctor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('peculiar_symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('causation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lab_reports', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('case_date', sa.Date(), nullable=False),
    sa.Column('case_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_case_appointment_id'), 'patient_case', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_patient_case_case_number'), 'patient_case', ['case_number'], unique=True)
    op.create_index(op.f('ix_patient_case_doctor_id'), 'patient_case', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_case_patient_id'), 'patient_case', ['patient_id'], unique=False)
    op.create_table('prescription',
    sa.Column('prescription_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('prescription_duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_up_advice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dietary_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avoidance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('prescription_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['patient_case.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_case_id'), 'prescription', ['case_id'], unique=False)
    op.create_index(op.f('ix_prescription_doctor_id'), 'prescription', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescription_prescription_number'), 'prescription', ['prescription_number'], unique=True)
    op.create_table('follow_up',
    sa.Column('subjective_improvement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objective_findings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aggravation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amelioration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('general_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=False),
    sa.Column('payment_confirmed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['patient_case.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_case_id'), 'follow_up', ['case_id'], unique=False)
    op.create_index(op.f('ix_follow_up_doctor_id'), 'follow_up', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_follow_up_prescription_id'), 'follow_up', ['prescription_id'], unique=False)
    op.create_table('prescription_medicine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_prescribed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medicine_medicine_id'), 'prescription_medicine', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_medicine_prescription_id'), 'prescription_medicine', ['prescription_id'], unique=False)
    op.create_table('onsite_consultation_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=True),
    sa.Column('follow_up_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_new_patient', sa.Boolean(), nullable=False),
    sa.Column('patient_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['patient_case.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_up.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_doctor_date', 'onsite_consultation_audit', ['doctor_id', 'created_at'], unique=False)
    op.create_index('idx_audit_idempotency', 'onsite_consultation_audit', ['idempotency_key'], unique=False)
    op.create_index('idx_audit_patient_phone', 'onsite_consultation_audit', ['patient_phone', 'created_at'], unique=False)
    op.create_index(op.f('ix_onsite_consultation_audit_appointment_id'), 'onsite_consultation_audit', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_onsite_consultation_audit_case_id'), 'onsite_consultation_audit', ['case_id'], unique=False)
    op.create_index(op.f('ix_onsite_consultation_audit_doctor_id'), 'onsite_consultation_audit', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_onsite_consultation_audit_idempotency_key'), 'onsite_consultation_audit', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_onsite_consultation_audit_patient_id'), 'onsite_consultation_audit', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onsite_consultation_audit_patient_id'), table_name='onsite_consultation_audit')
    op.drop_index(op.f('ix_onsite_consultation_audit_idempotency_key'), table_name='onsite_consultation_audit')
    op.drop_index(op.f('ix_onsite_consultation_audit_doctor_id'), table_name='onsite_consultation_audit')
    op.drop_index(op.f('ix_onsite_consultation_audit_case_id'), table_name='onsite_consultation_audit')
    op.drop_index(op.f('ix_onsite_consultation_audit_appointment_id'), table_name='onsite_consultation_audit')
    op.drop_index('idx_audit_patient_phone', table_name='onsite_consultation_audit')
    op.drop_index('idx_audit_idempotency', table_name='onsite_consultation_audit')
    op.drop_index('idx_audit_doctor_date', table_name='onsite_consultation_audit')
    op.drop_table('onsite_consultation_audit')
    op.drop_index(op.f('ix_prescription_medicine_prescription_id'), table_name='prescription_medicine')
    op.drop_index(op.f('ix_prescription_medicine_medicine_id'), table_name='prescription_medicine')
    op.drop_table('prescription_medicine')
    op.drop_index(op.f('ix_follow_up_prescription_id'), table_name='follow_up')
    op.drop_index(op.f('ix_follow_up_doctor_id'), table_name='follow_up')
    op.drop_index(op.f('ix_follow_up_case_id'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_prescription_prescription_number'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_doctor_id'), table_name='prescription')
    op.drop_index(op.f('ix_prescription_case_id'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_patient_case_patient_id'), table_name='patient_case')
    op.drop_index(op.f('ix_patient_case_doctor_id'), table_name='patient_case')
    op.drop_index(op.f('ix_patient_case_case_number'), table_name='patient_case')
    op.drop_index(op.f('ix_patient_case_appointment_id'), table_name='patient_case')
    op.drop_table('patient_case')
    op.drop_index(op.f('ix_finance_transaction_custom_field_value_transaction_id'), table_name='finance_transaction_custom_field_value')
    op.drop_index(op.f('ix_finance_transaction_custom_field_value_field_id'), table_name='finance_transaction_custom_field_value')
    op.drop_table('finance_transaction_custom_field_value')
    op.drop_index(op.f('ix_doctor_enum_preferences_enum_option_id'), table_name='doctor_enum_preferences')
    op.drop_index(op.f('ix_doctor_enum_preferences_doctor_id'), table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_option', table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_doctor_option', table_name='doctor_enum_preferences')
    op.drop_index('idx_doctor_enum_pref_doctor', table_name='doctor_enum_preferences')
    op.drop_table('doctor_enum_preferences')
    op.drop_index(op.f('ix_finance_transaction_doctor_id'), table_name='finance_transaction')
    op.drop_index(op.f('ix_finance_transaction_cash_book_id'), table_name='finance_transaction')
    op.drop_index('idx_transaction_nature_code', table_name='finance_transaction')
    op.drop_index('idx_transaction_deleted', table_name='finance_transaction')
    op.drop_index('idx_transaction_date', table_name='finance_transaction')
    op.drop_index('idx_transaction_category_code', table_name='finance_transaction')
    op.drop_table('finance_transaction')
    op.drop_index(op.f('ix_finance_cash_book_custom_field_cash_book_id'), table_name='finance_cash_book_custom_field')
    op.drop_index('idx_cash_book_custom_field_display_order', table_name='finance_cash_book_custom_field')
    op.drop_table('finance_cash_book_custom_field')
    op.drop_index(op.f('ix_enum_options_enum_type_id'), table_name='enum_options')
    op.drop_index('idx_enum_option_type_value', table_name='enum_options')
    op.drop_index('idx_enum_option_type_id', table_name='enum_options')
    op.drop_index('idx_enum_option_sort', table_name='enum_options')
    op.drop_index('idx_enum_option_active', table_name='enum_options')
    op.drop_table('enum_options')
    op.drop_index(op.f('ix_doctor_medicine_preference_medicine_id'), table_name='doctor_medicine_preference')
    op.drop_index(op.f('ix_doctor_medicine_preference_doctor_id'), table_name='doctor_medicine_preference')
    op.drop_table('doctor_medicine_preference')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index('idx_doctor_appointments', table_name='appointment')
    op.drop_index('idx_appointment_datetime', table_name='appointment')
    op.drop_table('appointment')
    op.drop_table('testimonials')
    op.drop_table('specializations')
    op.drop_table('services')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_patient_doctor_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_medicine_name'), table_name='medicine')
    op.drop_index(op.f('ix_medicine_created_by_doctor_id'), table_name='medicine')
    op.drop_table('medicine')
    op.drop_index(op.f('ix_finance_cash_book_doctor_id'), table_name='finance_cash_book')
    op.drop_table('finance_cash_book')
    op.drop_index('idx_enum_type_key', table_name='enum_types')
    op.drop_index('idx_enum_type_active', table_name='enum_types')
    op.drop_table('enum_types')
    op.drop_index(op.f('ix_doctor_followup_field_preference_field_name'), table_name='doctor_followup_field_preference')
    op.drop_index(op.f('ix_doctor_followup_field_preference_doctor_id'), table_name='doctor_followup_field_preference')
    op.drop_table('doctor_followup_field_preference')
    op.drop_index(op.f('ix_doctor_case_field_preference_field_name'), table_name='doctor_case_field_preference')
    op.drop_index(op.f('ix_doctor_case_field_preference_doctor_id'), table_name='doctor_case_field_preference')
    op.drop_table('doctor_case_field_preference')
    op.drop_index(op.f('ix_doctor_availability_exception_doctor_id'), table_name='doctor_availability_exception')
    op.drop_index('idx_doctor_exception_date', table_name='doctor_availability_exception')
    op.drop_table('doctor_availability_exception')
    op.drop_index(op.f('ix_doctor_availability_doctor_id'), table_name='doctor_availability')
    op.drop_index('idx_doctor_day', table_name='doctor_availability')
    op.drop_index('idx_doctor_availability', table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('services_and_treatments')
    op.drop_index(op.f('ix_sequence_counter_counter_type'), table_name='sequence_counter')
    op.drop_index('idx_counter_type_prefix', table_name='sequence_counter')
    op.drop_table('sequence_counter')
    op.drop_table('patient_success_stories')
    op.drop_table('hero_section')
    op.drop_table('contact_information')
    op.drop_table('about_doctor')
    # ### end Alembic commands ###
